@startuml

set namespaceSeparator /

class psmb/cron/scheduler {
	+Clear()
	+Emergency() *Job
	+Every(interval uint64) *Job
	+EveryWithName(interval uint64, name string) *Job
	+IsRunning() bool
	+Location(*time.Location)
	+NextRun() (*Job, time.Time)
	+Remove(*Job) bool
	+UpdateIntervalWithName(name string, interval uint64) bool
	+RemoveWithName(string) bool
	+PauseWithName(string) bool
	+PauseAll()
	+ResumeWithName(string) bool
	+ResumeAll()
	+RunPending()
	+Start()
	+Stop()
    +Len() int
    +Swap(i, j int)
    +Less(i, j int) bool
    ~runPending(now time.Time)
}

interface psmb/cron/Scheduler {
	+Clear()
	+Emergency() *Job
	+Every(interval uint64) *Job
	+EveryWithName(interval uint64, name string) *Job
	+IsRunning() bool
	+Location(*time.Location)
	+NextRun() (*Job, time.Time)
	+Remove(*Job) bool
	+UpdateIntervalWithName(name string, interval uint64) bool
	+RemoveWithName(string) bool
	+PauseWithName(string) bool
	+PauseAll()
	+ResumeWithName(string) bool
	+ResumeAll()
	+RunPending()
	+Start()
	+Stop()
}

"psmb/cron/scheduler" .|> "psmb/cron/Scheduler"

hide interface fields

@enduml