@startuml

set namespaceSeparator /

class psmb/mem-reader/readerTaskDataStore {
    ~idMap map[string]psmb.ReaderTask
    ~idName map[string]string
    ~nameID map[string]string
    ~nameMap map[string]psmb.ReaderTask
    +Add(name string, tid string, cmd string, req interface{})
    +DeleteAll()
    +DeleteTaskByID(tid string)
    +DeleteTaskByName(name string)
    +GetAll() interface{}
    +GetTaskByID(tid string) (interface{}, bool)
    +GetTaskByName(name string) (interface{}, bool)
    +UpdateAllTogglesByName(toggle bool)
    +UpdateIntervalByName(name string, interval uint64) error
    +UpdateToggleByName(name string, toggle bool) error
}

interface psmb/IReaderTaskDataStore {
    +Add(name string, tid string, cmd string, req interface{})
    +DeleteAll()
    +DeleteTaskByID(tid string)
    +DeleteTaskByName(name string)
    +GetAll() interface{}
    +GetTaskByID(tid string) (interface{}, bool)
    +GetTaskByName(name string) (interface{}, bool)
    +UpdateAllTogglesByName(toggle bool)
    +UpdateIntervalByName(name string, interval uint64) error
    +UpdateToggleByName(name string, toggle bool) error
}

"psmb/IReaderTaskDataStore" <|. "psmb/mem-reader/readerTaskDataStore"

hide interface fields

@enduml