@startuml

set namespaceSeparator /

class psmb/redis-writer/writerTaskDataStore {
    +Add(tid string, cmd string)
    +Delete(tid string)
    +Get(tid string) (string, bool)
    ~closeRedis()
    ~connectRedis() error
}

interface psmb/IWriterTaskDataStore {
    +Add(tid string, cmd string)
    +Delete(tid string)
    +Get(tid string) (string, bool)
}

"psmb/IWriterTaskDataStore" <|. "psmb/redis-writer/writerTaskDataStore"

hide interface fields

@enduml