@startuml

set namespaceSeparator /

class psmb/redis-history/dataStore {
    +Add(name string, data interface{}) error
    +Get(name string, limit int) (map[string]string, error)
    +GetAll(name string) (map[string]string, error)
    +GetLatest(name string) (string, error)
    ~closeRedis()
    ~connectRedis() error
}

interface psmb/IHistoryDataStore {
    +Add(name string, data interface{}) error
    +Get(name string, limit int) (map[string]string, error)
    +GetAll(name string) (map[string]string, error)
    +GetLatest(name string) (string, error)
}

"psmb/IHistoryDataStore" <|. "psmb/redis-history/dataStore"

caption @taka-wang

hide interface fields

@enduml