@startuml

node upstream
node psmbtcp
rectangle "worker pool" #LightBlue{
    Usecase worker1 #FFF
    Usecase worker2 #FFF
    Usecase worker... #FFF
}

node modbusd

left to right direction

upstream <-- worker1 : zmq
upstream <-- worker2 : zmq
upstream <-- worker... : zmq
worker1 <-- psmbtcp
worker2 <-- psmbtcp
worker... <-- psmbtcp

psmbtcp <-- modbusd : zmq



caption @taka-wang

@enduml
