@startuml

node scheduler
node modbusd
node upstream
node psmbtcp

rectangle "worker pool" #LightBlue{
    Usecase worker1 #FFF
    Usecase worker2 #FFF
    Usecase worker... #FFF
}

left to right direction

upstream <--> psmbtcp : zmq
psmbtcp <--> worker1
psmbtcp <--> worker2
psmbtcp <--> worker...
worker1 --> scheduler
worker2 --> scheduler
worker... --> scheduler
scheduler --> modbusd : zmq


caption @taka-wang

@enduml
