@startuml

node frontend
node psmbtcp
rectangle "mb-web" {
    node route
    rectangle "worker pool" #LightBlue{
        Usecase worker1 #FFF
        Usecase worker2 #FFF
        Usecase worker... #FFF
    }
}

node modbusd

left to right direction

frontend <-- worker1 : HTTP
frontend <-- worker2 : HTTP
frontend <-- worker... : HTTP
worker1 <-- psmbtcp : zmq
worker2 <-- psmbtcp : zmq
worker... <-- psmbtcp : zmq

psmbtcp <-- modbusd : zmq



caption @taka-wang

@enduml