@startuml

set namespaceSeparator /

skinparam classAttributeIconSize 0

class psmb/tcp/Service {
    +HandleRequest(cmd string, r interface{}) error
    +HandleResponse(cmd string, r interface{}) error
    +ParseRequest(msg []string) (interface{}, error)
    +ParseResponse(msg []string) (interface{}, error)
    +Start()
    +Stop()
    +Task(socket *zmq.Socket, req interface{})
    ~addToHistory(taskName string, data interface{})
    ~initZMQPub()
    ~initZMQSub()
    ~initZMQPoller()
    ~naiveResponder(cmd string, resp interface{}) error
}

interface psmb/IProactiveService {
    +HandleRequest(cmd string, r interface{}) error
    +HandleResponse(cmd string, r interface{}) error
    +ParseRequest(msg []string) (interface{}, error)
    +ParseResponse(msg []string) (interface{}, error)
    +Start()
    +Stop()
}

"psmb/IProactiveService" <|. "psmb/tcp/Service"

caption @taka-wang

hide interface fields

@enduml