@startuml

set namespaceSeparator /

skinparam classAttributeIconSize 0

class psmb/mem-filter/dataStore {
	+Add(name string, req interface{})
	+Get(name string) (interface{}, bool)
	+GetAll() interface{}
	+Delete(name string)
	+DeleteAll()
	+UpdateToggle(name string, toggle bool) error
	+UpdateAllToggles(toggle bool)
}

interface psmb/IFilterDataStore {
	+Add(name string, req interface{}) error
	+Get(name string) (interface{}, bool)
	+GetAll() interface{}
	+Delete(name string)
	+DeleteAll()
	+UpdateToggle(name string, toggle bool) error
	+UpdateAllToggles(toggle bool)
}

"psmb/IFilterDataStore" <|. "psmb/mem-filter/dataStore"

caption @taka-wang

hide interface fields

@enduml