@startuml

set namespaceSeparator /

skinparam classAttributeIconSize 0

class psmb/mem-reader/dataStore {
    +Add(name string, tid string, cmd string, req interface{})
    +DeleteAll()
    +DeleteTaskByID(tid string)
    +DeleteTaskByName(name string)
    +GetAll() interface{}
    +GetTaskByID(tid string) (interface{}, bool)
    +GetTaskByName(name string) (interface{}, bool)
    +UpdateAllToggles(toggle bool)
    +UpdateIntervalByName(name string, interval uint64) error
    +UpdateToggleByName(name string, toggle bool) error
}

interface psmb/IReaderTaskDataStore {
    +Add(name string, tid string, cmd string, req interface{}) error
    +DeleteAll()
    +DeleteTaskByID(tid string)
    +DeleteTaskByName(name string)
    +GetAll() interface{}
    +GetTaskByID(tid string) (interface{}, bool)
    +GetTaskByName(name string) (interface{}, bool)
    +UpdateAllToggles(toggle bool)
    +UpdateIntervalByName(name string, interval uint64) error
    +UpdateToggleByName(name string, toggle bool) error
}

"psmb/IReaderTaskDataStore" <|. "psmb/mem-reader/dataStore"

caption @taka-wang

hide interface fields

@enduml