@startuml

set namespaceSeparator /

skinparam classAttributeIconSize 0

class psmb/redis-writer/dataStore {
    +Add(tid string, cmd string)
    +Delete(tid string)
    +Get(tid string) (string, bool)
}

interface psmb/IWriterTaskDataStore {
    +Add(tid string, cmd string)
    +Delete(tid string)
    +Get(tid string) (string, bool)
}

"psmb/IWriterTaskDataStore" <|. "psmb/redis-writer/dataStore"

caption @taka-wang

hide interface fields

@enduml